name: Pipeline
on: 
  schedule:
    # Every Friday at 11PM UTC
    - cron: '0 23 * * 5'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make image test
  
  build-stable:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: egnd/docker:stable
          build-args: DOCKER_VERSION=stable-git

  build-latest:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: egnd/docker:latest
          build-args: DOCKER_VERSION=git

  build-20:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: egnd/docker:20
          build-args: DOCKER_VERSION=20-git
