name: Pipeline
on: 
  schedule:
    # Every Friday at 11PM UTC
    - cron: '0 23 * * 5'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make image test
  
  build-stable:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      JOB_IMAGE_TAG: stable
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: egnd/docker:${{env.JOB_IMAGE_TAG}}
          build-args: DOCKER_VERSION=${{env.JOB_IMAGE_TAG}}

  build-latest:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      JOB_IMAGE_TAG: latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: egnd/docker:${{env.JOB_IMAGE_TAG}}
          build-args: DOCKER_VERSION=${{env.JOB_IMAGE_TAG}}

  build-20:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      JOB_IMAGE_TAG: 20
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: egnd/docker:${{env.JOB_IMAGE_TAG}}
          build-args: DOCKER_VERSION=${{env.JOB_IMAGE_TAG}}

  build-18:
    runs-on: ubuntu-latest
    needs: [test]
    env:
      JOB_IMAGE_TAG: 18
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DHLGN }}
          password: ${{ secrets.DHPWD }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: egnd/docker:${{env.JOB_IMAGE_TAG}}
          build-args: DOCKER_VERSION=${{env.JOB_IMAGE_TAG}}
